version: '2'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  config-server:
    image: config-server
    container_name: config-server
    ports:
      - 8888:8888
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  api-gateway:
    image: api-gateway
    container_name: api-gateway
    ports:
      - 8080:8080
    depends_on:
      - rabbitmq
      - config-server
      - discovery-service
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  discovery-service:
    image: discovery-service
    container_name: discovery-service
    ports:
      - 8761:8761
    depends_on:
      - config-server
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  movies-service:
    image: movies-service
    container_name: movies-service
    ports:
      - 8090:8090
    depends_on:
      - rabbitmq
      - config-server
      - discovery-service
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  tv-shows-service:
    image: tv-shows-service
    container_name: tv-shows-service
    ports:
      - 8070:8070
    depends_on:
      - rabbitmq
      - config-server
      - discovery-service
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  rating-service:
    image: rating-service
    container_name: rating-service
    ports:
      - 8060:8060
    depends_on:
      - rabbitmq
      - config-server
      - discovery-service
      - movies-service
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  trace-service:
    image: trace-service
    container_name: trace-service
    ports:
      - 9411:9411
    depends_on:
      - rabbitmq
      - config-server
      - discovery-service
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  monitoring:
    image: monitoring
    container_name: monitoring
    ports:
      - 8020:8020
      - 8989:8989
    depends_on:
      - rabbitmq
      - config-server
      - discovery-service
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"